[package]
name = "seton"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"
bevy_egui = "0.16.0"
bevy_prototype_lyon = "0.6.0"
rand = "0.8.5"
ndarray = "0.15.6"

[workspace]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3