[package]
name = "seton"
version = "0.1.3"
edition = "2021"

[dependencies]
bevy = "0.15.3"
bevy_egui = "0.33"
bevy_prototype_lyon = "0.13"
rand = "0.9.0"
ndarray = "0.16.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3