[package]
name = "seton"
version = "0.1.3"
edition = "2021"

[dependencies]
bevy = "0.14"
bevy_egui = "0.29"
bevy_prototype_lyon = "0.12"
rand = "0.8.5"
ndarray = "0.16.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3